#!/usr/bin/env python3

# Copyright      2017  Hossein Hadian

# Apache 2.0
# This script converts a BPE-encoded text to normal text. It is used in scoring

import sys, io
import string
import re
infile = io.TextIOWrapper(sys.stdin.buffer, encoding='utf-8')
output = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

punctuations = "!(),.?;:'-\""
escaped_punctuations = re.escape(punctuations)

for line in infile:
  words = line.strip().split()
  uttid = words[0]
  transcript = ''.join(words[1:])
  transcript = transcript.replace('|', ' ')
  split_transcript = " ".join(re.split("([{}])".format(escaped_punctuations),
                                       transcript)).strip()
  output.write(uttid + ' ' + split_transcript + '\n')
